---
title: "wc_ratio"
author: "Kyllan Wunder"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Covid19Wastewater)
library(dplyr)
library(ggplot2)
library(anytime)
library(ggpubr)
```


```{r get data}
data(Case_data, package = "Covid19Wastewater")
cases <- Case_data
cases$date <- anydate(cases$date)

data(WasteWater_data, package = "Covid19Wastewater")
waste <- WasteWater_data
waste <- waste %>% rename(date = sample_collect_date, Site = wwtp_name)
waste$date <- anydate(waste$date)

cases_madison <- cases %>% filter(Site == "Madison")
waste_madison <- waste %>% filter(grepl('Madison', Site)) %>% select(1,7,10,12,14) 
waste_madison$Site <- paste0("Madison")

waste_madison <- waste_madison %>% group_by(date)  %>% summarise(n1_sars_cov2_conc = sum(n1_sars_cov2_conc), n2_sars_cov2_conc = sum(n2_sars_cov2_conc), ppmov_conc = sum(ppmov_conc))

```




```{r madison}

madison_data = merge(x=cases_madison, y=waste_madison, by="date", all = TRUE)
madison_data <- na.omit(madison_data)

#ggplot(madison_data, aes(date,log(n1_sars_cov2_conc)/log(FirstConfirmed))) +
#   geom_point() +
#   scale_y_log10()

day_2 <- lubridate::ymd('2020-09-02') #F2020 start date
day_3 <- lubridate::ymd('2021-09-08') #F2021 start date
day_4 <- lubridate::ymd('2020-12-10') #F2020 end date
day_5 <-lubridate::ymd('2021-12-15') #F2021 end date

day_6 <- lubridate::ymd('2021-01-19') #S2021 start date
day_7 <- lubridate::ymd('2022-01-25') #S2022 start date
day_8 <- lubridate::ymd('2021-05-07') #S2021 end date
day_9 <-lubridate::ymd('2022-05-13') #S2022 end date

ggplot(madison_data, aes(date,FirstConfirmed)) +
  geom_point() +
  scale_y_log10() +
     annotate(geom = "vline",
             x = c(day_2, day_3, day_4, day_5,day_6,day_7,day_8,day_9),
             xintercept = c(day_2, day_3, day_4, day_5,day_6,day_7,day_8,day_9),
             linetype = c("solid", "solid", "solid", "solid","solid", "solid", "solid", "solid")) +
    annotate(geom = "text",
             label = c("F20 UW start", "F21 UW start","F20 UW end", "F21 UW end","S21 UW start", "S22 UW start", "S21 UW end", "S22 UW end"),
             x = c(day_2, day_3, day_4, day_5,day_6,day_7,day_8,day_9),
             y = c(1, 1,1,1,1, 1,1,1),
             angle = 90, 
             vjust = 1) 
ggplot(madison_data, aes(date,n1_sars_cov2_conc)) +
  geom_point() +
  scale_y_log10() 

# ggplot(madison_data, aes(date,log(n1_sars_cov2_conc/FirstConfirmed))) +
#   geom_point() +
#   scale_y_log10()

#try with smoothing

```

```{r}
madison_data <- madison_data %>% rename(site = Site)
```

```{r remove outliers}
#
rmoutliersmadison <- computeJumps(madison_data)
rmoutliersmadison <- rankJumps(rmoutliersmadison)
rmoutliersmadison <- computeRankQuantiles(rmoutliersmadison)
rmoutliersmadison <- flagOutliers(rmoutliersmadison,9)
#rmoutliersmadison <- rmoutliersmadison[!(rmoutliersmadison$FlaggedOutlier=="TRUE"),]

# ggplot(rmoutliersmadison, aes(date,log(n1_sars_cov2_conc)/FirstConfirmed)) +
#   geom_point() +
#   scale_y_log10()

flagged <- rmoutliersmadison[(rmoutliersmadison$FlaggedOutlier=="TRUE"),]
 ggplot(rmoutliersmadison, aes(x=date)) +
   geom_point(aes(y=log(n1_sars_cov2_conc)/FirstConfirmed, color=rmoutliersmadison$FlaggedOutlier)) +
   scale_y_log10()
```


```{r}

waste  <- waste %>% select(1,7,10,12,14) 
```

```{r all}
waste <- waste %>% group_by(date)  %>% summarise(n1_sars_cov2_conc = sum(n1_sars_cov2_conc), n2_sars_cov2_conc = sum(n2_sars_cov2_conc), ppmov_conc = sum(ppmov_conc))

cases <- cases %>% group_by(date)  %>% summarise(FirstConfirmed = sum(FirstConfirmed))

wisc_data = merge(x=cases, y=waste, by="date", all = TRUE)
wisc_data <- na.omit(wisc_data)


ggplot(wisc_data, aes(date,log(n1_sars_cov2_conc)/FirstConfirmed)) +
  geom_point() + 
  scale_y_log10()




```




```{r}
library(zoo)
wisc_data <- wisc_data %>% mutate(rollingaverage = zoo::rollmean(n1_sars_cov2_conc, k = 7, fill = NA))

ggplot(wisc_data, aes(date,log(rollingaverage/FirstConfirmed))) +
  geom_point() + 
  scale_y_log10()

ggplot(wisc_data, aes(date,log(rollingaverage)/FirstConfirmed)) +
  geom_point() + 
  scale_y_log10()

ggplot(wisc_data, aes(date,log(rollingaverage)/log(FirstConfirmed))) +
  geom_point() + 
  scale_y_log10()

ggplot(wisc_data, aes(date,rollingaverage/FirstConfirmed)) +
  geom_point() + 
  scale_y_log10()
```

