---
title: "offset_by_variant"
author: "Kyllan Wunder"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DSIWastewater)
library(dplyr)
library(ggplot2)
library(anytime)
library(ggpubr)
library(lubridate)
library(zoo)
library(reshape2)
library(scales)
library(plotly)
library(tidyverse)
library(psych)
library(timetk)
```


```{r data}

data(Case_data, package = "DSIWastewater")
cases <- Case_data

data(WasteWater_data, package = "DSIWastewater")
waste <- WasteWater_data

data(Covariants_data, package = "DSIWastewater")
covar <- Covariants_data



```

```{r functions}

MSE <- function(baseVal, meanVal){
  ret <- mean((baseVal - meanVal)^2)
  return(ret)
}


Offset <-function(length, startdate, enddate, casesdf, wastedf){
  
  wastedf <- subset(wastedf, anydate(date)> anydate(startdate) & anydate(date) < anydate(enddate))
  casesdf <- subset(casesdf, anydate(date)> anydate(startdate) & anydate(date) < anydate(enddate))

  wastedf <- wastedf%>% 
  group_by(date)%>% 
  summarise(N1 = mean(N1),
            N2 = mean(N2),
            PMMoV = mean(PMMoV)) %>% 
  mutate(geo_mean = exp((log(N1) + log(N2))/2)) %>% 
  drop_na(geo_mean)



  casesdf <- casesdf %>%
    group_by(date) %>% 
    summarise(conf_case = mean(conf_case)) %>%
    mutate(rollingaverage = rollmean(conf_case, k=7, fill = NA)) %>%
    drop_na(rollingaverage)

  offsetresults <- data.frame(matrix(ncol = 7, nrow = 0))
  
  for(i in -length:length){
  
    wasteTemp <- wastedf %>% 
      mutate(tempdate = as.Date(wastedf$date + i))
    
    temp <- merge(casesdf, wasteTemp, by.x = "date" ,by.y = "tempdate") 
    
    temp <- temp %>% 
      mutate(proportionRolling = temp$geo_mean/temp$rollingaverage,
            proportion = temp$geo_mean/temp$conf_case, 
            mse = MSE(temp$geo_mean/temp$rollingaverage,
            mean(temp$geo_mean/temp$rollingaverage)))
    
    temp <- na.omit(temp)
    new <- c(i,mean(temp$proportion),
              mean(temp$proportionRolling),
              mean(temp$mse), 
              cor(temp$geo_mean,temp$rollingaverage,method = "pearson"), 
              cor(temp$geo_mean,temp$rollingaverage,method = "kendall"),
              cor(temp$geo_mean,temp$rollingaverage,method = "spearman"))
    
    offsetresults[nrow(offsetresults) + 1, ] <- new  
  }

  offsetresults <- offsetresults %>% rename(wdateoffset=X1,
                                            wcratio=X2,
                                            wcratiorolling=X3,
                                            meanMSErolling=X4,
                                            corilationPearson=X5,
                                            corilationKendall=X6,
                                            corilationSpearman=X7)
  return(offsetresults)
}

#' Title
#'
#' @param data 
#'
#' @return
#' @export
#'
#' @examples
Graph <- function(data,title){
  wc <- ggplot(data, aes(x=wdateoffset, y=wcratio)) +
    geom_point() +
    geom_point(data = data[which.max(data$wcratio),], color = "red") +    
    ylab("Waste-to-case ratio") +
    xlab("Wastewater Offset") +
    ggtitle("Waste-to-case ratio")
  
  wcrolling <- ggplot(data, aes(x=wdateoffset, y=wcratiorolling)) +
    geom_point() + 
    geom_point(data = data[which.min(data$wcratiorolling),], color = "red") +
    ylab("Wastewater to Case ratio") +
    xlab("Wastewater Offset") +
    ggtitle("Rolling waste-to-case ratio") +
    geom_text(data = data[which.min(data$wcratiorolling),], aes(wdateoffset,wcratiorolling, label = paste(wdateoffset, " " ,sep = "\n")))

  mse <- ggplot(data, aes(x=wdateoffset, y=meanMSErolling)) +
    geom_point() +
    geom_point(data = data[which.min(data$meanMSErolling),], color = "red") +
    ylab("Rolling Average MSE") +
    xlab("Wastewater Offset") +
    ggtitle("Rolling average MSE") +
    geom_text(data = data[which.min(data$meanMSErolling),], aes(wdateoffset,meanMSErolling, label = paste(wdateoffset, " " ,sep = "\n")))

  pearson <- ggplot(data, aes(x=wdateoffset, y=corilationPearson)) +
    geom_point() +
    geom_point(data = data[which.max(data$corilationPearson),], color = "red") +
    ylab("Pearson Correlation") +
    xlab("Wastewater Offset") +
    ggtitle("Pearson") +
    geom_text(data = data[which.max(data$corilationPearson),], aes(wdateoffset,corilationPearson, label = paste(" " ,wdateoffset,sep = "\n")))
  
  kendall <- ggplot(data, aes(x=wdateoffset, y=corilationKendall)) +
    geom_point()+
    geom_point(data = data[which.max(data$corilationKendall),], color = "red") +
    ylab("Kendall correlation") +
    xlab("Wastewater Offset") +
    ggtitle("Kendall") +
    geom_text(data = data[which.max(data$corilationKendall),], aes(wdateoffset,corilationKendall, label = paste(" " ,wdateoffset,sep = "\n")))
  
  spearman <- ggplot(data, aes(x=wdateoffset, y=corilationSpearman)) +
    geom_point() +
    geom_point(data = data[which.max(data$corilationSpearman),], color = "red") +
    ylab("Spearman Correlation") +
    xlab("Wastewater Offset") +
    ggtitle("Spearman") +
    geom_text(data = data[which.max(data$corilationSpearman),], aes(wdateoffset,corilationSpearman, label = paste(" " ,wdateoffset,sep = "\n")))
  
  grid.arrange(wc,wcrolling,mse,pearson,kendall,spearman,ncol=2,bottom=title)
}
```


```{r}

outputfinal <- Offset(20, as.Date("2020-01-01"), as.Date("2023-01-01"), cases, waste)

Graph(outputfinal,"All Wisconsin data over all time")


```


```{r}

covar$category <- row.names(covar)
onlycovar <- covar[-c(1,2)]
mdfr <- melt(onlycovar, id.vars = "category")

p <- ggplot(mdfr, aes(factor(category,levels = c(1:69)), value, fill = variable)) +
    geom_bar(position = "fill", stat = "identity") +
    scale_y_continuous(labels = percent) +
    xlab("Week") +
    ylab("Covariant Percent")

ggplotly(p)


percentages <- mdfr %>%
  group_by(category) %>%
  mutate(sum = sum(value), percent = value/sum, majority = case_when(percent > .5 ~ paste(variable)))

per <- percentages %>% drop_na(majority)
  

p2 <- ggplot(per, aes(x=category, y=percent,color=majority)) +
  geom_point()
  
  ggplotly(p2)
#9-20 2020-08-17 2021-01-18  S.677H.Robin1
#25-29 2021-03-29 2021-05-24 X20I..Alpha..V1.
#32-43 2021-07-05 2021-12-06 X21J..Delta.
#44-50 2021-12-20 2022-03-14 X21K..Omicron.
#51-54 2022-03-28 2022-05-09 X21L..Omicron.
#55-56 2022-05-23 2022-06-06 X22C..Omicron.
#58-67 2022-07-04 2022-11-07 X22B..Omicron.
#69-   2022-12-05 
```
```{r}
#2 weeks before and 2 weeks after
#2020-08-17 2021-01-18
outputfinal <- Offset(10, as.Date("2020-08-03"), as.Date("2021-02-01"), cases, waste)
Graph(outputfinal,"24 weeks, S.677H.Robin1")
#2021-03-29 2021-05-24
outputfinal <- Offset(10, as.Date("2021-03-15"), as.Date("2021-06-07"), cases, waste)
Graph(outputfinal,"6 weeks, X20I..Alpha..V1.")
#2021-07-05 2021-12-06
outputfinal <- Offset(10, as.Date("2021-06-21"), as.Date("2021-12-20"), cases, waste)
Graph(outputfinal,"24 weeks, X21J..Delta.")
#2021-12-20 2022-03-14
outputfinal <- Offset(10, as.Date("2021-12-06"), as.Date("2022-03-28"), cases, waste)
Graph(outputfinal,"14 weeks, X21K..Omicron.")
#2022-03-28 2022-05-09
outputfinal <- Offset(10, as.Date("2022-03-14"), as.Date("2022-05-23"), cases, waste)
Graph(outputfinal, "8 weeks, X21L..Omicron.")
#2022-05-23 2022-06-06
outputfinal <- Offset(10, as.Date("2022-05-09"), as.Date("2022-06-20"), cases, waste)
Graph(outputfinal, "4 weeks, X22B..Omicron.")
#2022-07-04 2022-11-07
outputfinal <- Offset(10, as.Date("2022-06-20"), as.Date("2022-11-28"), cases, waste)
Graph(outputfinal, "20 weeks, X22B..Omicron.")
#2022-12-05 -
outputfinal <- Offset(10, as.Date("2022-11-28"), as.Date("2023-01-01"), cases, waste)
Graph(outputfinal, "2+ weeks, X22E..Omicron.")


#add time widow to dates 
#add 1 time window
```
```{r}
#6 month chunks
outputfinal <- Offset(10, as.Date("2020-08-01"), as.Date("2021-02-01"), cases, waste)
Graph(outputfinal,"1")

outputfinal <- Offset(10, as.Date("2021-02-01"), as.Date("2021-08-01"), cases, waste)
Graph(outputfinal,"2")

outputfinal <- Offset(10, as.Date("2021-08-01"), as.Date("2022-02-01"), cases, waste)
Graph(outputfinal,"3")

outputfinal <- Offset(10, as.Date("2022-02-01"), as.Date("2022-08-01"), cases, waste)
Graph(outputfinal,"4")

outputfinal <- Offset(10, as.Date("2022-08-01"), as.Date("2023-02-01"), cases, waste)
Graph(outputfinal, "5")

```



```{r}
wastedf <- waste
casesdf <- cases

#wasteccf <- function(wastedf, casesdf){
  wastedf <- drop_na(wastedf, date)
  casesdf <- drop_na(casesdf, date)
  startdate <- max(c(min(wastedf$date),min(casesdf$date)))
  enddate <- min(c(max(wastedf$date),max(casesdf$date)))
  #enddate <- as.Date("2022-01-01")
  wastedf <- subset(wastedf, anydate(date)> anydate(startdate) & anydate(date) < anydate(enddate))
  casesdf <- subset(casesdf, anydate(date)> anydate(startdate) & anydate(date) < anydate(enddate))

  wastedf <- wastedf%>% 
  group_by(date)%>% 
  summarise(N1 = mean(N1),
            N2 = mean(N2),
            PMMoV = mean(PMMoV)) %>% 
  mutate(geo_mean = exp((log(N1) + log(N2))/2)) %>% 
  drop_na(geo_mean)



  casesdf <- casesdf %>%
    group_by(date) %>% 
    summarise(conf_case = mean(conf_case)) %>%
    mutate(rollingaverage = rollmean(conf_case, k=7, fill = NA)) %>%
    drop_na(rollingaverage)
  
  dim(wastedf)
  min(wastedf$date)
  max(wastedf$date)
  dim(casesdf)
  min(casesdf$date)
  max(casesdf$date)
  
  
  ccf(wastedf$geo_mean,casesdf$conf_case)
  ccf(wastedf$geo_mean,casesdf$rollingaverage)
  
  wastecaseccfmerg <- merge(wastedf, casesdf, by.x = "date", by.y="date") 
  wastecaseccf <- wastecaseccfmerg %>% 
    select('geo_mean','conf_case')
  lag_ts <- ts(na.omit(wastecaseccf))
  ts_info(lag_ts)
  plot(lag_ts)
ts_plot(lag_ts)

ccf(lag_ts[, c(1)], lag_ts[, c(2)], 
    lag.max = 1000,
    main = "Cros-Correlation Plot")
acf(wastedf$geo_mean,casesdf$rollingaverage)




wastecasepts <- wastecaseccfmerg %>% pivot_longer(cols = c(geo_mean, conf_case), names_to = "names", values_to = "value") 

wastecasepts %>% plot_time_series(.date_var = date,
                      .value = value,
                   .facet_vars = names)


wastecasepts %>%
  group_by(names) %>% 
  plot_acf_diagnostics(.date_var = date,
                       .value = value,
                       .show_white_noise_bars = T)

wastecaseccfmerg %>% 
  plot_acf_diagnostics(.date_var = date,
                       .value = geo_mean,
                       .ccf_vars = conf_case,
                       .show_ccf_vars_only = T)

#}
#wasteccf(waste,cases)


```

