---
title: "alte_case_flags"
author: "Marlin"
date: '2022-07-27'
output: pdf_document
editor_options: 
  chunk_output_type: inline
---


```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)
```

```{r create case data in right format}
library(Covid19Wastewater)
```

```{r create case flags}
#load Case_data into the environment
data(Case_data, package = "Covid19Wastewater")


#restrict Case data to only Madison data
Case_DF <- Case_data[Case_data$site == "Madison",]


#restrict Case data to dates after 2021-02-01
Case_DF <- Case_DF[Case_DF$date  >= as.Date("2021-02-01"),]


#get the case flags
Case_DF <- buildCaseAnalysisDF(Case_DF)


CaseRegressionOutput <- buildRegressionEstimateTable(DataMod = Case_DF, 
    RunOn = c("case.Per100K", "weekly_avg_case_Per100K"),
    SplitOn = "site", DaysRegressed = 7)

```

```{r}
library(tidyr)
library(plotly)

Plot_DF <- CaseRegressionOutput%>%
  select(date, Method, lmreg_slope)%>%
  pivot_wider(names_from = Method, values_from = lmreg_slope)

SlopeComp <- Plot_DF%>%
  ggplot()+
  geom_point(aes(x = case.Per100K,
                 y = weekly_avg_case_Per100K, info = date))+
  geom_abline(color = "red")

ggplotly(SlopeComp)

SlopeComp <- Plot_DF%>%
  ggplot(aes(x = date))+
  geom_line(aes(y = case.Per100K, color = "cases slope"))+
  geom_line(aes(y = weekly_avg_case_Per100K, color = "smooth cases slope"))+
  geom_hline(yintercept = 5)

ggplotly(SlopeComp)

cor(Plot_DF$case.Per100K, 
    Plot_DF$weekly_avg_case_Per100K,
    use = "pairwise.complete.obs")
```

```{r}
library(dplyr)

BaseCaseFlagOutput <- CaseRegressionOutput%>%
  filter(Method == "case.Per100K")%>%
  classifyCaseRegression(slopeThreshold = 2)%>%
  select(site, date, case_flag, slope_switch_flag)%>%
  rename(Base_case_flag = case_flag, Base_switch_flag = slope_switch_flag)

AltCaseFlagOutput <- CaseRegressionOutput%>%
  filter(Method == "weekly_avg_case_Per100K")%>%
  classifyCaseRegression(slopeThreshold = 0)%>%
  select(site, date, case_flag, slope_switch_flag)%>%
  rename(Alt_case_flag = case_flag, Alt_switch_flag = slope_switch_flag)

Full_Flag_DF <- inner_join(BaseCaseFlagOutput, AltCaseFlagOutput, by = c("date","site"))

#25	6	9
#BaseCaseFlagOutput,AltCaseFlagOutput
countFlags(Full_Flag_DF, group = c("site"))

mean(BaseCaseFlagOutput$Base_case_flag)
```


```{r Single plot code}


#define color scheme for the plots to have
colorScheme <- ggplot2::scale_color_manual(values = 
                                c("Base_switch_flag" = "red",
                                "Alt_switch_flag" = "blue",
                                "Both" = "green",
                                "weekly_avg_case_Per100K" = "deeppink",
                                "Loess" = "black",
                                "case.Per100K" = "brown",
                                "sars_cov2_adj_load_log10" = "grey"),
                                limits = force)

library(ggplot2)
#use old graphing code to 
createFlagGraph_plot(Case_DF, Full_Flag_DF,
                                  Flag1 = "Base_switch_flag",
                                  Flag2 = "Alt_switch_flag",
                                      PointVal = "case.Per100K",
                                      LineVal = c("weekly_avg_case_Per100K"),
                                      facetFormula = " ~ site")+ 
  colorScheme+
  scale_y_log10()

#BaseCaseFlagOutput,AltCaseFlagOutput
```

```{r stacked plot}

createFlagGraph_plot(Case_DF, Full_Flag_DF,
                                  Flag1 = "Base_switch_flag",
                                  Flag2 = "Alt_switch_flag",
                                      PointVal = "case.Per100K",
                                      LineVal = c("weekly_avg_case_Per100K"),
                                      facetFormula = " ~ site")


A <- createFlagGraph_plot(Case_DF, Full_Flag_DF,
                          Flag1 = "Base_switch_flag",
                          PointVal  = c("case.Per100K"),
                          facetFormula = " ~ site")+ 
  colorScheme+
  scale_y_log10()

B <- createFlagGraph_plot(Case_DF, Full_Flag_DF,
                          Flag1 = "Alt_switch_flag",
                          LineVal = c("weekly_avg_case_Per100K"),
                          facetFormula = " ~ site")+ 
  colorScheme+
  scale_y_log10()

patchwork::wrap_plots(A,B, ncol = 1, guides = 'collect')
```

