---
title: "EXP_Smoothing"
author: "Marlin"
date: '2022-07-08'
output: html_document
---

```{r load packages}
library(DSIWastewater)
library(dplyr)
library(zoo)
```

```{r exp}
ParameterGuess <- function(DF,InVar, Base, max){
  temp <- DF%>%
    filter(!is.na((!!sym(InVar))))%>%
    summarise(n=n())
  span <- min(c(Base/temp$n, max))#More can be done here
  return(span)
}

ExpSmoothMod <- function(DF,InVar="sars_cov2_adj_load_log10",
                         OutVar="EXP", alpha="guess", beta="guess",
                         Filter = NULL ){
  
  if(alpha=="guess"){
    alpha <- ParameterGuess(DF,InVar, 35.6, .4)
  }
  if(beta=="guess"){
    beta <- ParameterGuess(DF,InVar, 8.9, .4)
  }
  if(!is.null(Filter)){
    OutDF <- DF%>%
      filter((!!sym(Filter)) | is.na(!!sym(InVar)))%>%
      mutate(!!OutVar := NA)
    
    DF <- DF%>%
      filter(!(!!sym(Filter))  & !is.na(!!sym(InVar)))
  }else{
    OutDF <- DF%>%
      filter(is.na(!!sym(InVar)))%>%
      mutate(!!OutVar := NA)
    
    DF <- DF%>%
      filter(!is.na(!!sym(InVar)))
  }
  
  DF <- DF%>%
    arrange(date)
  
  DF[[OutVar]] <- robets::robets(y=DF[[InVar]],
                          model = "AAN",
                          beta  = beta,
                          alpha=alpha,
                          k = 3)$fitted
  DF <- DF%>%
    bind_rows(OutDF)
  
  return(DF)
}
```

```{r three messure exp smoothing}
lag <- dplyr::lag(1:10,3)
weightedSmooth <- function(DF,InVar="sars_cov2_adj_load_log10",
                         OutVar="3Smooth"){
  
  SmoothVec <- DF[[InVar]]
  DF[[OutVar]] <- .5*SmoothVec + 
                  .25*lag(SmoothVec,1) + 
                  .125*lag(SmoothVec,2)
  return(DF)
}
```

```{r create worksheet4}
data(wastewater_data, package = "DSIWastewater")

workset4_data <- buildWorkSheet4(wastewater_data)

workset4_data <- workset4_data[workset4_data$WWTP == "Madison MSD WWTF",]

workset4_Smooth_data <- workset4_data%>%
                    LoessSmoothMod()%>%
                    ExpSmoothMod(alpha = 0.07688985,
                                 beta = 0.01922246)%>%
  arrange(date)%>%
  weightedSmooth()%>%
  mutate(SevSmooth = rollmean(sars_cov2_adj_load_log10, k=7, fill=NA, align="right"))

workset4_Smooth_data

```

```{r run regression analysis}
reg_estimates_data <- buildRegressionEstimateTable(workset4_Smooth_data,
                               RunOn = c("sars_cov2_adj_load_log10",
                                "SevSmooth",
                                "EXP",
                                "3Smooth",
                                "Loess"))
head(reg_estimates_data)
```

```{r metrics}
prepDataForMessure <- function(DF){
  Cat.map <- c("major increase" = 2, "moderate increase" = 1, 
              "fluctuating" = 0, "no change" = 0,
              "moderate decrease" = -1, "major decrease" = -2)   
  num_reg_estimates_data <- DF%>%
    select(WWTP,date,Method,Catagory)%>%
    mutate(Catagory = Cat.map[Catagory])

  RetDF <- num_reg_estimates_data%>%
    filter(Method == "Loess")%>%
    select(WWTP,date, Loess = Catagory)%>%
    full_join(num_reg_estimates_data)%>%
    select(WWTP,date,Method,Catagory,Loess)
  return(RetDF)
}


Messure_reg_estimates_data <- prepDataForMessure(reg_estimates_data)
Messure_reg_estimates_data%>%
  group_by(Method)%>%
  mutate(diff = abs(Catagory - Loess),
         BigDiff = diff >= 2,
         vol = abs(Catagory-lag(Catagory)),
         Bigvol = vol>= 2)%>%
  summarise(diff = mean(diff),
            PerBigDiff = mean(BigDiff) * 100,
            vol = mean(vol, na.rm = TRUE),
            PerBigvol = mean(Bigvol, na.rm = TRUE) * 100
            )
#meanerror(Wide_reg_estimates_data, Loess, EXP)
```


```{r Compare methods,fig.width=6, eval = FALSE}

createMethodCompareBar_Plot(reg_estimates_data)

#reg_estimates_data%>%
#  filter(Method == "SevSmooth")
```

```{r make DHS plot, fig.height=15,fig.width=14.25, warning = FALSE}
createDHSMethod_Plot(reg_estimates_data, workset4_Smooth_data, 
                 PointVal = c( "sars_cov2_adj_load_log10"),
                 LineVal = c("Loess","EXP", "SevSmooth", "3Smooth"))
```