---
title: "sampleFrequency"
author: "Kyllan Wunder"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DSIWastewater)
library(dplyr)
library(ggplot2)
library(anytime)
library(noise)
library(tidyr)
library(zoo)
library(lubridate)
```


```{r}
year_week <- function(x,base) week(x) - week(base) + 52*(year(x) - year(base))

data(WasteWater_data, package = "DSIWastewater")

sfdata <- WasteWater_data 


sfdata <- sfdata %>% 
  group_by(site) %>% 
  mutate(rollaverage = rollmean(log(as.numeric(PMMoV)), k=7, fill = NA)) %>% 
  drop_na(rollaverage) %>% ungroup()



sfdata <- sfdata %>% group_by(site, week = year_week(anydate(date), "2020-01-01")) %>% mutate(sampleFrequency = n()) %>% ungroup()

sfdata <- sfdata %>% group_by(site) %>% 
  mutate(avgSampleFrequency = mean(sampleFrequency)) %>% ungroup()



```

```{r}
sfdata <- sfdata %>%  group_by(site) %>%  mutate(max = max(sampleFrequency)) %>% filter(sampleFrequency <= 6) 
```


```{r}
sitessubset <- c("Madison","Marshfield","Black River Falls","Sparta","Wausau","Clintonville","Appleton","Red Cliff","Racine")




sfdata %>% filter(max > 1) %>% mutate(sampleFrequency = as.factor(sampleFrequency)) %>% filter(grepl(paste(sitessubset, collapse='|'), site)) %>%
ggplot(aes(week, sampleFrequency,color=sampleFrequency)) +
  geom_point() +
  facet_wrap(~site) +
  ggtitle("Sample Frequency by Week") +
  xlab("Weeks") + 
  ylab("Sample Frequency") +
  labs(fill=" ")
  


```

```{r}

sfdata %>% group_by(week) %>% mutate(weeklyavg = mean(sampleFrequency)) %>%
ggplot(aes(week, weeklyavg,color=weeklyavg)) +
  geom_point() +
  ggtitle("Sample Frequency by Week") +
  xlab("Weeks") + 
  ylab("Sample Frequency") +
  labs(fill=" ")



sfdata %>% group_by(date) %>% tally() %>%
ggplot(aes(date, n,color=weekdays(anydate(date)))) +
  geom_point() +
  ggtitle("Sample Frequency by Day") +
  xlab("Days") + 
  ylab("Sample Frequency") +
  labs(fill=" ")

testtype <- sfdata %>% ggplot(aes(date, N1,color=pcr_type)) +
  geom_point() +
  ggtitle("Test Type") +
  labs(fill=" ")
ggplotly(testtype)
```

```{r}
siteStats <- sfdata %>% select(1,14,32,33,34) %>% group_by(site) %>% mutate(maxsf = max(sampleFrequency),startdate = min(anydate(sample_collect_date)), enddate = max(anydate(sample_collect_date)),minweek = min(week),maxweek = max(week))



```

```{r}
siteStats %>% 
  ggplot(mapping = aes(x = reorder(site,minweek), y = minweek)) +
    geom_pointrange(mapping = aes(ymin = maxweek, ymax = minweek))
siteStats %>% 
  ggplot(mapping = aes(x = reorder(site,maxweek), y = maxweek)) +
    geom_pointrange(mapping = aes(ymin = maxweek, ymax = minweek))
```


