---
title: "Comprehensive Random Analysis of Covid-19"
output: 
  
  html_document:
    code_folding: hide
date: "2023-01-24"
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
run_base <- FALSE
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
```

```{r include = FALSE}
library(DSIWastewater)
library(dplyr)
library(ggplot2)
library(tidyr)
library(zoo)
set.seed(123)
```


```{r plot function}
imp_ploting <- function(temp_mod){
  ImpData <- as.data.frame(randomForest::importance(temp_mod))
  ImpData$Var.Names <- row.names(ImpData)


ggplot(ImpData, aes(x=reorder(Var.Names, -`IncNodePurity`), y=`%IncMSE`)) +
  geom_segment( aes(x=reorder(Var.Names, -`IncNodePurity`), xend=reorder(Var.Names, -`IncNodePurity`), y=0, yend=`%IncMSE`), color="skyblue") +
  geom_point(aes(size = IncNodePurity), color="blue", alpha=0.6) +
  theme_light() +
  coord_flip() +
  theme(
    legend.position="bottom",
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank())
}
```

```{r data prep}
library(DSIWastewater)
data(pop_data, package = "DSIWastewater")
data(WasteWater_data , package = "DSIWastewater")
data(Case_data , package = "DSIWastewater")
data(Covariants_data, package = "DSIWastewater")


t_df <- Covariants_data%>%
  select(-total_sequences)
t_df$main_variant<-colnames(t_df)[apply(t_df, 1, which.max)]
manga_df <- t_df%>%
  mutate(dumby_merge_var = floor(as.numeric(lubridate::ymd(week)) / 7),
         main_variant = as.factor(main_variant))%>%
  select(dumby_merge_var, main_variant)

case_merge_df <- Case_data%>%
  mutate(roll_prob_case = rollmean(prob_case, 7 ,na.pad = TRUE))


data.select.1 <- WasteWater_data%>%
  left_join(pop_data)%>%
  left_join(case_merge_df)%>%
  mutate(site = as.factor(site),
         regions = as.factor(regions),
         #N1 = ifelse(N1 >= n1_sars_cov2_lod, N1, n1_sars_cov2_lod/2),
         #N2 = ifelse(N2 >= n2_sars_cov2_lod, N2, n2_sars_cov2_lod/2),
         roll_prob_case = roll_prob_case / pop,
         #cov_flow_pop_norm = sqrt(N1 * N2) * flow / pop,
         pop = log(pop))%>%
  mutate(dumby_merge_var = floor((floor(as.numeric(date) / 7) - 1)/2)*2 + 1 )%>%
  left_join(manga_df)%>%
  select(-dumby_merge_var)

linear_model <- lm(log(roll_prob_case + 1) ~ log(sqrt(N1*N2) + 1), 
                                data = data.select.1, na.action = na.exclude)
data.select.1$resid <- resid(linear_model)
```


```{r mod fit}
library(randomForest)
library(randomForestExplainer)
to_numeric = c("date", "bod", "created_on", "last_modified_on", "test_result_date", "sample_collect_time")
to_factor = c("county", "pcr_type", "n1_sars_cov2_lod", "n2_sars_cov2_lod", "lab_submitter")



to_log = c("flow", "ph", "conductivity", "n1_lod", "n2_lod", "n1_loq", "n2_loq", "capacity_mgd", "PMMoV")


to_drop <- c("created_on", "last_modified_on", "test_result_date", "site", "county")

weird_drop <- c("n1_sars_cov2_error", "n1_num_ntc_amplify", "n1_num_no_target_control", "n2_sars_cov2_error", "n2_num_ntc_amplify", "n2_num_no_target_control", "zipcode")

cheating_drop <- c("N1", "N2", "tests", "prob_case", "conf_case", "roll_prob_case",
                   "avg_sars_cov2_conc", "cov_flow_pop_norm", "sample_id")


resid_df <- data.select.1%>%
  mutate(across(to_numeric, as.numeric),
         across(to_factor, as.factor),
         across(to_log, ~log(abs(.x) + 1)))

train_df <- resid_df%>%
  select(where(~(is.numeric(.x) || is.factor(.x))))%>%
  select(-one_of(to_drop))%>%
  select(-one_of(cheating_drop))%>%
  select(-one_of(weird_drop))%>%
  select(where( ~!all(is.na(.x))))


Covariants_data%>%
  filter(week == max(week))%>%
  select(where(~min(.x)>0))
```


```{r model fit}
resid_mod <-randomForest(resid ~ ., data = train_df, ntree=100,
                  na.action = na.roughfix, importance=TRUE, keep.inbag=TRUE)
resid_mod
imp_ploting(resid_mod)

#resid_df%>%
#  select(where(~!(is.numeric(.x) || is.factor(.x))))
#resid_df%>%
#  summarise(across(everything(), ~sum(is.na(.x))/n()))


as.data.frame(randomForest::importance(resid_mod))%>%
  arrange(desc(!!sym('%IncMSE')))

#we compared a bunch of stuff!!!
#we improved case modeling
#simple rule improves model
#more forceful using the random forest to predict () gives upper bounds of covariate 
```

```{r viz, eval = FALSE}
graph_df <- train_df%>%
  na.roughfix()%>%
  select(regions:main_variant)#%>%
  #select(partial_plot_names)

library(forestFloor)
ff = forestFloor(resid_mod, graph_df, calc_np=T)
for(i in 1:12){
  Col = fcol(ff, cols = i, outlier.lim = 2.5)
  plot(ff, plot_seq = 1:12, col = Col, plot_GOF = T)
}
```

```{r, eval = FALSE}

x = randomForest::partialPlot(resid_mod, graph_df, 
                              x.var = names(graph_df)[[4]],
                              plot = FALSE)
{
plot(x, 
     xlab = names(graph_df2)[[4]], 
     ylab = "conditional change of forest model output",
     main = "difference is proportional to bcov")
abline(a = 0, b = .1)
}


prop_df <- data.select.2.sc%>%
  rename(bcov = diff_bcov_rec_rate)%>%
  mutate(bcov_mod_diff = -.1*bcov  + resid,
         cond_bcov_mod_diff = ifelse( bcov <= 2,
                              -.1*bcov + resid,
                              resid),
         bcov_mod_conc = -.1*bcov  + log(avg_sars_cov2_conc + 1),
         cond_bcov_mod_conc = ifelse( bcov <= 2,
                              -.1*bcov + log(avg_sars_cov2_conc + 1),
                              log(avg_sars_cov2_conc + 1))
         )

var_sum_df <- prop_df%>%
  summarise(name = "variance",
            'base value' = var(resid), 
            'linear normalization' = var(bcov_mod_diff),
            'conditional normalization' = var(cond_bcov_mod_diff))


cor_sum_df <- prop_df%>%
  summarise(name = "corelation",
            'base value' = cor(log(avg_sars_cov2_conc + 1), case_rate), 
            'linear normalization' = cor(bcov_mod_conc, case_rate),
            'conditional normalization' = cor(cond_bcov_mod_conc, case_rate))


rbind(var_sum_df, cor_sum_df)


summary(lm(case_rate ~ avg_sars_cov2_conc,data = data.select.3))
summary(lm(case_rate ~ (avg_sars_cov2_conc + avg_sars_cov2_conc*bcov_rec_rate) + regions, data = data.select.3))
```


```{r plot_df}

quick_plot <- function(DF, filt_site){
  defult_DF <- DF%>%
    filter(site == filt_site)
  
  show_plot <- defult_DF%>%
    ggplot(aes(x = as.Date(date)))+
    geom_point(aes(y = log(roll_prob_case + 1), color = "real case value"))+
    geom_line(aes(y = lin_pred_case, color = "linear model prediction"),
              data = filter(defult_DF, !is.na(lin_pred_case)))+
    geom_line(aes(y = lin_pred_case + resd_pred, color = "random forest prediction"),
              data = filter(defult_DF, !is.na(lin_pred_case), !is.na(resd_pred)))+
    geom_vline(xintercept = split_date)
  return(show_plot)
}

quick_mse <- function(DF){
  mse_DF <- DF%>%
    filter(date >= split_date)%>%
    mutate(true_cases = log(roll_prob_case + 1),
           lm_error = true_cases - lin_pred_case,
           tree_error = true_cases - lin_pred_case - resd_pred)%>%
    summarise(lm_mse = mean(lm_error**2, na.rm = TRUE),
              tree_mse = mean(tree_error**2, na.rm = TRUE))
  return(mse_DF)
}
#model_split_df%>%
#  select(site, pop)%>%
#  group_by(site)%>%
#  summarise(pop = mean(pop), n = n())%>%
#  distinct()%>%
#  arrange(n)#Peshtigo, Platteville, Hudson, Madison
#unique(model_split_df$pcr_type)
```


To get the best possible handle we explore splitting the data into a test and training
set where they are separated by time due to the autocorelation. This can create
problems because the digital PCR change was recent so we removed DPCR measurements
from the test.



```{r model data prep}
library(plotly)
model_split_df <- resid_df%>%
  select(where(~(is.numeric(.x) || is.factor(.x))))%>%
  select(-one_of(weird_drop))%>%
  filter(!is.na(date))%>%
  filter(pcr_type != "dPCR")%>%
  #filter(site == "Madison")%>%
  arrange(date)%>%
  mutate(avg_sars_cov2_conc = log(sqrt(N1*N2) + 1))


min_date = min(model_split_df$date, na.rm = TRUE)
split_date = min_date + 3 * (max(model_split_df$date, na.rm = TRUE) 
                  - min_date)/ 4

lm_train_split_df <- model_split_df%>%
  filter(date < split_date)%>%
  select(where( ~!all(is.na(.x))))%>%
  select(-date)

test_split_df <- model_split_df%>%
  filter(date >= split_date)%>%
  select(where( ~!all(is.na(.x))))%>%
  filter(site %in% unique(lm_train_split_df$site))%>%
  select(-date)

model_split_df <- model_split_df%>%
  filter(site %in% unique(lm_train_split_df$site))
```

```{r data prep lm comp}

linear_mod <- lm(log(roll_prob_case + 1) ~ avg_sars_cov2_conc:site, 
                                data = lm_train_split_df, na.action = na.roughfix)

lm_train_split_df$resid <- resid(linear_mod)

test_split_df <- test_split_df%>%
  mutate(resid = log(roll_prob_case + 1) - predict(linear_mod, test_split_df))

train_split_df <- lm_train_split_df%>%
  select(-one_of(cheating_drop))%>%
  select(-one_of(to_drop))%>%
  select(one_of(names(test_split_df)))
```


```{r model fitting}

resid_split_mod <-randomForest(resid ~ ., data = train_split_df, ntree = 100,
                  na.action = na.roughfix)


Form <- case_rate ~ avg_sars_cov2_conc| . - avg_sars_cov2_conc - resid #sars_cov2_adj_load
#library(rsample)
linear_forest_model <- random_linear_forest(data = lm_train_split_df,
                                     num_tree = 20, 
                                     model_formula = Form,
                                     max_depth = Inf,
                                     verbose = FALSE)
#lm_train_split_df
pred = predict(forest_model, rand_tree_df)
```

```{r model predicting}

test_split_pred_df <- test_split_df%>%
  select(-one_of(cheating_drop))%>%
  select(-one_of(to_drop))%>%
  na.roughfix()

train_split_pred_df <- train_split_df%>%
  na.roughfix()

#fit lm components
model_split_df$lin_pred_case <- c(predict(linear_mod, lm_train_split_df),
                                  predict(linear_mod, test_split_df))

model_split_df$resd_pred <- c(predict(resid_split_mod, train_split_pred_df),
                                  predict(resid_split_mod, test_split_pred_df))
```

```{r plot model in piced options}
quick_mse(model_split_df)
quick_plot(model_split_df, "Peshtigo")
quick_plot(model_split_df, "Platteville")
quick_plot(model_split_df, "Hudson")
quick_plot(model_split_df, "Madison")
```