---
title: "HFGTrendCorr"
author: "Marlin"
date: "2022-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



```{r cars}
library(DSIWastewater)
library(dplyr)
library(ggplot2)
library(tidyr)
data("HFGWaste_data", package = "DSIWastewater")

```

```{r}

#crazy agressive method
hfg_outlier_detection <- function(small_vec){
  upbound_vec <- quantile(small_vec, probs = .7, na.rm = TRUE)
  retVec = ifelse(small_vec > upbound_vec,
                  NA, small_vec)
  retVec = ifelse(retVec == 0, NA, retVec)
  return(retVec)
}

hfg_waste_filt_df <- HFGWaste_data%>%
  select(site, date, Filter, Well, N1, N2, PMMOV, BCoV, HF183, CrP)%>%
  group_by(date,site)%>%
  mutate(across(N1:CrP, hfg_outlier_detection))


#HFGWaste_data%>%
#select(site, date, Filter, Well, N1, N2, PMMOV, BCoV, HF183, CrP)%>%
#  filter(site == "Platteville",
#         date == as.Date("2021-03-01"))
```

```{r}
trend_df <- hfg_waste_filt_df%>%
  group_by(site)%>%
  group_split()%>%
  lapply(loessSmoothMod, InVar = "N1", OutVar = "N1")%>%
  lapply(loessSmoothMod, InVar = "N2", OutVar = "N2")%>%
  lapply(loessSmoothMod, InVar = "PMMOV", OutVar = "PMMOV")%>%
  lapply(loessSmoothMod, InVar = "HF183", OutVar = "HF183")%>%
  lapply(loessSmoothMod, InVar = "CrP", OutVar = "CrP")%>%
  bind_rows()

SumVariance <- trend_df%>%
  summarise(N1 = var(N1 ,na.rm = TRUE),
            N2 = var(N2 ,na.rm = TRUE),
            PMMOV = var(PMMOV ,na.rm = TRUE),
            HF183 = var(HF183 ,na.rm = TRUE),
            CrP = var(CrP ,na.rm = TRUE))%>%
  mutate(log = FALSE)

SumVariance%>%
  pivot_longer(N1:CrP)%>%
  ggplot()+
  geom_col(aes(x = name, y = value))


library(ggcorrplot)
trend_df%>%
  select(N1, N2, PMMOV, HF183, CrP)%>%
  cor(use = "complete.obs")%>%
  ggcorrplot()


trend_df%>%
  pivot_longer(N1:CrP)%>%
  ggplot(aes(x = date, y = value, color = name))+
  geom_point()+
  facet_wrap(~site)
```


```{r fig.height = 15, fig.width= 15}

library(GGally)
trend_df%>%
  select(-Filter, - Well)%>%
  ggpairs( aes(colour = site, alpha = 0.4))
```


```{r}
log_trend_df <- hfg_waste_filt_df%>%
  mutate(log_N1 = log(N1),
         log_N2 = log(N2),
         log_PMMOV = log(PMMOV),
         log_HF183 = log(HF183),
         log_CrP = log(CrP))%>%
  group_by(site)%>%
  group_split()%>%
  lapply(loessSmoothMod, InVar = "log_N1", OutVar = "log_N1")%>%
  lapply(loessSmoothMod, InVar = "log_N2", OutVar = "log_N2")%>%
  lapply(loessSmoothMod, InVar = "log_PMMOV", OutVar = "log_PMMOV")%>%
  lapply(loessSmoothMod, InVar = "log_HF183", OutVar = "log_HF183")%>%
  lapply(loessSmoothMod, InVar = "log_CrP", OutVar = "log_CrP")%>%
  bind_rows()%>%
  select(site, date,Filter, Well, log_N1, log_N2, log_PMMOV, log_HF183, log_CrP)

logVariance <- log_trend_df%>%
  summarise(N1 = var(log_N1, na.rm = TRUE),
            N2 = var(log_N2, na.rm = TRUE),
            PMMOV = var(log_PMMOV, na.rm = TRUE),
            HF183 = var(log_HF183, na.rm = TRUE),
            CrP = var(log_CrP, na.rm = TRUE))%>%
  select(N1:CrP)%>%
  mutate(log = TRUE)

logVariance%>%
  pivot_longer(N1:CrP)%>%
  ggplot()+
  geom_col(aes(x = name, y = value))

log_trend_df%>%
  select(log_N1, log_N2, log_PMMOV, log_HF183, log_CrP)%>%
  cor(use = "complete.obs")%>%
  ggcorrplot()

log_trend_df%>%
  pivot_longer(log_N1:log_CrP)%>%
  ggplot(aes(x = date, y = value, color = name))+
  geom_point(size = .5)+
  facet_wrap(~site)
```

```{r fig.height = 15, fig.width= 15}
library(GGally)
log_trend_df%>%
  select(-Filter, -Well)%>%
  ggpairs(aes(colour = site, alpha = 0.4))
```

```{r}
sub_var <- bind_rows(SumVariance, logVariance)
sub_var
```

