---
title: "High level normalization work"
author: "Marlin"
date: "2022-12-02"
output: html_document
---


```{r load libs}
library(dplyr)
library(ggplot2)
```

```{r}
library(DSIWastewater)
data(Case_data, package = "DSIWastewater")

#restrict Case data to only Madison data
Case_DF <- Case_data


#restrict Case data to dates after 2021-02-01
Case_DF <- Case_DF[Case_DF$date  >= as.Date("2020-9-10"),]

#get the case flags
Case_DF <- buildCaseAnalysisDF(Case_DF)

Case_DF <- Case_DF[,c(1:2, 5, 7)]

data(WasteWater_data, package = "DSIWastewater")

#restrict Waste data to only Madison data
baseWaste_DF <- WasteWater_data

Temp <- baseWaste_DF%>%
  mutate(n1_sars_cov2_lod = gsub(" ", "", tolower(n1_sars_cov2_lod)) == 
        "yes", n2_sars_cov2_lod = gsub(" ", "", tolower(n2_sars_cov2_lod)) == 
        "yes", n1_sars_cov2_conc = ifelse(n1_sars_cov2_lod, as.numeric(n1_lod)/2, 
        n1_sars_cov2_conc), n2_sars_cov2_conc = ifelse(n2_sars_cov2_lod, 
        as.numeric(n2_lod)/2, n2_sars_cov2_conc), population_served = as.numeric(gsub(",", 
        "", population_served))) %>% 
  select(wwtp_name, sample_collect_date, 
        population_served, n1_sars_cov2_conc, n2_sars_cov2_conc, 
        average_flow_rate, ppmov_conc) %>%
  rename(site = wwtp_name, date = sample_collect_date)%>%
  mutate(date = as.Date(date, format = "%m/%d/%Y"))%>%
  mutate(site = ifelse(site == "Madison MSD WWTF" , "Madison", site))

FullDF <- full_join(Case_DF, Temp, by = c("date","site"))%>%
  group_by(site)%>%
  mutate(pop = mean(population_served, na.rm = TRUE),
         FirstConfirmed.Per100K = pastwk.avg.casesperday.Per100K)%>%
  ungroup()


hist(log(FullDF$FirstConfirmed.Per100K) - .6*log(FullDF$n1_sars_cov2_conc))
diff <- log(FullDF$FirstConfirmed.Per100K) - .6*log(FullDF$n1_sars_cov2_conc)

cor(diff, log(FullDF$n1_sars_cov2_conc), use  = "pairwise.complete.obs")
cor(diff, log(FullDF$FirstConfirmed.Per100K), use  = "pairwise.complete.obs")

hist(log(FullDF$FirstConfirmed.Per100K))
hist(.6*log(FullDF$n1_sars_cov2_conc))


```




```{r plot}
toShow <- sample(unique(FullDF$site), 4)

quick_plot <- function(df, x){
  df%>%
    filter(site %in% toShow)%>%
    ggplot(aes(y = FirstConfirmed.Per100K, 
               x = !!sym(x),
               color = site))+
    geom_smooth(method = "lm")+
    geom_point()+
    guides(color = FALSE)+
    scale_y_log10()+
    scale_x_log10()
}
FullDF%>%
  quick_plot("n1_sars_cov2_conc")

FullDF%>%
  mutate(n1_sars_cov2_conc_pop = n1_sars_cov2_conc / pop)%>%
  quick_plot("n1_sars_cov2_conc_pop")

FullDF%>%
  mutate(n1_sars_cov2_conc_ppmov = n1_sars_cov2_conc / ppmov_conc)%>%
  quick_plot("n1_sars_cov2_conc_ppmov")

```



```{r lm stuff}
lm_DF1 <- FullDF%>%
  group_by(site)%>%
  filter(!is.na(log(FirstConfirmed.Per100K)), !is.na(log(n1_sars_cov2_conc)))%>%
  summarise(yinter = coef(lm(log(FirstConfirmed.Per100K) ~ log(n1_sars_cov2_conc)))[1],
            slope = coef(lm(log(FirstConfirmed.Per100K) ~ log(n1_sars_cov2_conc)))[2])

lm_DF2 <- FullDF%>%
  group_by(site)%>%
  filter(!is.na(log(FirstConfirmed.Per100K)), 
         !is.na(log(n1_sars_cov2_conc)),
         !is.na(log(ppmov_conc)))%>%
  summarise(yinter = coef(lm(log(FirstConfirmed.Per100K) ~
                               log(n1_sars_cov2_conc/abs(ppmov_conc))))[1],
            slope = coef(lm(log(FirstConfirmed.Per100K) ~ 
                              log(n1_sars_cov2_conc/abs(ppmov_conc))))[2])

lm_DF3 <- FullDF%>%
  group_by(site)%>%
  filter(!is.na(log(FirstConfirmed.Per100K)), 
         !is.na(log(n1_sars_cov2_conc)),
         !is.na(log(ppmov_conc)))%>%
  summarise(yinter = coef(lm(log(FirstConfirmed.Per100K) ~
                               log(n1_sars_cov2_conc/pop)))[1],
            slope = coef(lm(log(FirstConfirmed.Per100K) ~ 
                              log(n1_sars_cov2_conc/pop)))[2])

lm_DF1%>%
  ggplot(aes(x = slope, y = yinter))+
  geom_point()

lm_DF2%>%
  ggplot(aes(x = slope, y = yinter))+
  geom_point()

lm_DF3%>%
  ggplot(aes(x = slope, y = yinter))+
  geom_point()
```